# -*- coding: utf-8 -*-

# DRIVER_SQL = '{SQL Server Native Client 11.0};'
DRIVER_SQL = '{SQL Server};'

# SERVER_SQL = '113.190.253.193,1433\\AZETSRV;'
SERVER_SQL = '222.252.27.8,1433\\AZETSRV;'
DATABASE_SQL = 'CSDLTayBacUAT;'
USER_SQL = 'taybac;'
PASSWORD_SQL = 'techvify@123;'

DATABASE_POSTGRES = 'ks'
USER_POSTGRES = 'postgres'
PASSWORD_POSTGRES = '1'
HOST_POSTGRES = '10.101.3.204'
PORT_POSTGRES = 5432

Rabbit = 'amqp://guest:guest@52.220.224.131:5672/%2f'

Mongo = 'mongodb://fimo:fimo!54321@10.101.3.204:27017/ks'
Mongo_db = "ks"
Mongo_collection = "map_services"

server = '10.101.3.204'
admin = "fimo"
password = "Mrvm3CVEvr8JGet9"

staticAgs = r"E:\SourceCode\tmact_2019\data\connect_information\ArcgisPublishServer.ags"
db = r'E:\SourceCode\tmact_2019\data\connect_information\ks_connection.sde'

REF_TABLE = {
    "tbl_fc_lotrinhdc": {
        "table": "tbl_fc_lotrinhdc",
        "id": "id_nhatky",
        "ref_table": "tbl_nhatkydc",
        "ref_id": "id",
        "field": "MaNhatKyDC"
    },
    "tbl_fc_diemks": {
        "table": "tbl_fc_diemks",
        "id": "id_tuyenlt",
        "ref_table": "tbl_fc_lotrinhdc",
        "ref_id": "id",
        "field": "MaLoTrinh"
    }
}

OBJ_CASE = {
    "anh": "Anh",
    "bacdithuong": "BacDiThuong",
    "bachamluong": "BacHamLuong",
    "bac_dt": "Bac_DT",
    "banve": "BanVe",
    "banve_dientich": "Banve_DienTich",
    "banve_tq": "Banve_TQ",
    "baomat": "BaoMat",
    "bien_doi": "Bien_doi",
    "bieuhien": "BieuHien",
    "cqcapphep": "CQCapPhep",
    "caodogieng": "CaoDoGieng",
    "caodohao": "CaoDoHao",
    "chieudai": "ChieuDai",
    "chieudaituyen": "ChieuDaiTuyen",
    "chieudai_met": "ChieuDai_met",
    "chieurong": "ChieuRong",
    "chieusau": "ChieuSau",
    "chubien": "ChuBien",
    "chudautu": "ChuDauTu",
    "congthuckhoangvat": "CongThucKhoangVat",
    "cuongdodongdat": "CuongDoDongDat",
    "da_chuaquang": "Da_chuaquang",
    "da_vayquanh": "Da_vayquanh",
    "dacdiem_dc": "Dacdiem_DC",
    "dacdiem_ks": "Dacdiem_KS",
    "danhphap_bd": "DanhPhap_BD",
    "diadanh": "DiaDanh",
    "dientich": "DienTich",
    "dientichcam": "DienTichCam",
    "docaogieng": "DoCaoGieng",
    "docaoh": "DoCaoH",
    "docaolo": "DoCaoLo",
    "dosaugieng": "DoSauGieng",
    "dosauhao": "DoSauHao",
    "doanhnghiepkt": "DoanhNghiepKT",
    "doituongcam": "DoiTuongCam",
    "doituongdieutra": "DoiTuongDieuTra",
    "donviqd": "DonViQD",
    "donvith": "DonViTH",
    "donvituvan": "DonViTuVan",
    "donvitn": "DonviTN",
    "donvitn_tl": "DonviTN_TL",
    "donvithanhlap": "DonviThanhLap",
    "filepath": "FilePath",
    "file_anhnan": "File_AnhNan",
    "ghi_chu": "Ghi_chu",
    "giayphepkt": "GiayPhepKT",
    "giaypheptd": "GiayPhepTD",
    "gioi": "Gioi",
    "goccam_mattruot": "GocCam_MatTruot",
    "gocnghieng": "GocNghieng",
    "hamluong": "HamLuong",
    "hamluong_tb": "Hamluong_TB",
    "he": "He",
    "hetoado": "HeToaDo",
    "hientrang": "HienTrang",
    "hientranglk": "HientrangLK",
    "hinhthai_tq": "Hinhthai_TQ",
    "hoathach": "HoaThach",
    "hole_id": "Hole_ID",
    "huongcam_mattruot": "HuongCam_MatTruot",
    "huyen": "Huyen",
    "id": "ID",
    "id_bienchat": "ID_BienChat",
    "id_ctgieng": "ID_CTGieng",
    "id_cthao": "ID_CTHao",
    "id_ctlo": "ID_CTLo",
    "id_captltn": "ID_CapTLTN",
    "id_da": "ID_DA",
    "id_dvtc": "ID_DVTC",
    "id_danhphap": "ID_DanhPhap",
    "id_diemks": "ID_DiemKS",
    "id_dutgay": "ID_DutGay",
    "id_huyen": "ID_Huyen",
    "id_ks": "ID_KS",
    "id_ks_dikem": "ID_KS_dikem",
    "id_khudgks": "ID_KhuDGKS",
    "id_khutdks": "ID_KhuTDKS",
    "id_lotrinhdc": "ID_LoTrinhDC",
    "id_magma": "ID_Magma",
    "id_nhatky": "ID_NhatKy",
    "id_nhomks": "ID_NhomKS",
    "id_phieuctlo": "ID_PhieuCTLo",
    "id_tcdcks": "ID_TCDCKS",
    "id_tqdientichdg": "ID_TQDienTichDG",
    "id_tqdientichtd": "ID_TQDienTichTD",
    "id_tinh": "ID_Tinh",
    "id_tramtich": "ID_TramTich",
    "id_tuyenlt": "ID_TuyenLT",
    "id_tyle": "ID_TyLe",
    "id_xa": "ID_Xa",
    "id_khoangsannhole": "ID_khoangsannhole",
    "id_khuvucdgks": "Id_KhuVucDGKS",
    "id_khuvuctdks": "Id_KhuVucTDKS",
    "isdean": "IsDeAn",
    "khlt": "KHLT",
    "khlt_bv": "KHLT_BV",
    "kh_kv": "Kh_kv",
    "kh_nguyento": "Kh_nguyento",
    "khoangvatkhac": "KhoangVatKhac",
    "khoiluonggieng": "KhoiLuongGieng",
    "khoiluonghaovl": "KhoiLuongHaoVL",
    "khoiluonglo": "KhoiLuongLo",
    "khuvuc": "KhuVuc",
    "khuvucks": "KhuVucKS",
    "khuvucnc": "KhuVucNC",
    "kinhtuyentruc": "KinhTuyenTruc",
    "kyhieukhoangvat": "KyHieuKhoangVat",
    "kyhieunguyento": "KyHieuNguyenTo",
    "kyhieu_ks": "KyHieu_KS",
    "kyhieu_ks_dikem": "KyHieu_KS_dikem",
    "kyhieuks": "KyhieuKS",
    "layerid": "LayerID",
    "layername": "LayerName",
    "loaicongtacdodien": "LoaiCongTacDoDien",
    "loaicongtacdotruongluc": "LoaiCongTacDoTruongLuc",
    "loaicongtacdotu": "LoaiCongTacDoTu",
    "loaicongtacdoxa": "LoaiCongTacDoXa",
    "loaidks": "LoaiDKS",
    "loaids": "LoaiDS",
    "loaida": "LoaiDa",
    "loaidutgay": "LoaiDutGay",
    "loaihinhcam": "LoaiHinhCam",
    "loaionhiem": "LoaiONhiem",
    "loai_ks": "Loai_KS",
    "loaimau": "Loaimau",
    "mdnc": "MDNC",
    "mota_dks": "MoTa_DKS",
    "mucdich": "MucDich",
    "mucdichkhoan": "MucDichKhoan",
    "mucdo": "MucDo",
    "mucdobieuhien": "MucDoBieuHien",
    "mucdonghiencuu": "MucDoNghienCuu",
    "mucdobienchat": "MucdoBienChat",
    "mucdo_nc": "Mucdo_NC",
    "muichieu": "MuiChieu",
    "nam": "Nam",
    "namkt": "NamKT",
    "namnoplt": "NamNopLT",
    "namtc": "NamTC",
    "namxd": "NamXD",
    "ngayks": "NgayKS",
    "ngayketthuc": "NgayKetThuc",
    "ngaykhoicong": "NgayKhoiCong",
    "ngayqd": "NgayQD",
    "nguoiks": "NguoiKS",
    "nguonvon": "NguonVon",
    "nguon_goc": "Nguon_goc",
    "nguon_tailieu": "Nguon_tailieu",
    "nhom": "Nhom",
    "nhomdanhphap": "NhomDanhPhap",
    "nhomkhoangsan": "NhomKhoangSan",
    "nhomtobd": "NhomToBD",
    "objectid": "ObjectID",
    "pha": "Pha",
    "phamvidongdat": "PhamViDongDat",
    "phuhetang": "PhuHeTang",
    "phuongkeodai": "PhuongKeoDai",
    "phuongphapdao": "PhuongPhapDao",
    "phuongvi": "PhuongVi",
    "phuongphapkhoan": "PhuongphapKhoan",
    "quimo": "QuiMo",
    "quymo": "QuyMo",
    "rgb_color": "RGB_Color",
    "sh_diem": "SH_Diem",
    "sohieuhaovl": "SoHieuHaoVL",
    "sohieulo": "SoHieuLo",
    "sohieuvanh": "SoHieuVanh",
    "soqd": "SoQD",
    "soqdgiayphep": "SoQDGiayPhep",
    "tn_tl": "TN_TL",
    "tp_doikientao": "TP_DoiKienTao",
    "tacgia": "Tacgia",
    "tainguyen": "TaiNguyen",
    "tap": "Tap",
    "tap_phan": "Tap_Phan",
    "tenbc": "TenBC",
    "tenbv": "TenBV",
    "tenbando": "TenBanDo",
    "tenbanvekvdt": "TenBanVeKVDT",
    "tenbaocao": "TenBaoCao",
    "tends": "TenDS",
    "tendanhphap": "TenDanhPhap",
    "tendean": "TenDeAn",
    "tendiem": "TenDiem",
    "tendientich": "TenDienTich",
    "tengieng": "TenGieng",
    "tenhetang": "TenHeTang",
    "tenks": "TenKS",
    "tenkv": "TenKV",
    "tenkvcamhdks": "TenKVCamHDKS",
    "tenkhoangsan": "TenKhoangSan",
    "tenkhoangvat": "TenKhoangVat",
    "tenlk": "TenLK",
    "tenloaibd": "TenLoaiBD",
    "tennguyento": "TenNguyenTo",
    "tenphuche": "TenPhucHe",
    "tento": "TenTo",
    "tentuyen": "TenTuyen",
    "tenvung": "TenVung",
    "ten_bv": "Ten_BV",
    "ten_kv": "Ten_KV",
    "ten_tq": "Ten_TQ",
    "ten_nguyento": "Ten_nguyento",
    "thanhphanth": "ThanhPhanTH",
    "thanhphan_kv": "Thanhphan_KV",
    "thenam": "TheNam",
    "thietdokhoan": "ThietDoKhoan",
    "thoigiandt": "ThoiGianDT",
    "thong": "Thong",
    "tietdien": "TietDien",
    "tietdienlo": "TietDienLo",
    "tinh": "Tinh",
    "tinhchatdutgay": "TinhChatDutGay",
    "toadomienglox": "ToaDoMiengLoX",
    "toadomiengloy": "ToaDoMiengLoY",
    "toadox": "ToaDoX",
    "toadoy": "ToaDoY",
    "toanvanqd": "ToanVanQD",
    "truluong": "TruLuong",
    "tuoidc": "TuoiDC",
    "tuong": "Tuong",
    "tuyen": "Tuyen",
    "tuyenhao": "TuyenHao",
    "tyle_bd": "TyLe_BD",
    "tyle": "Tyle",
    "vitri": "ViTri",
    "vitridialy": "ViTriDiaLy",
    "vitrihanhchinh": "ViTriHanhChinh",
    "x": "X",
    "xa": "Xa",
    "y": "Y",
    "z": "Z"
}

LIST_SERVICE = {
  "tbl_fc_bandodiamao": "Lớp bản đồ địa mạo",
  "tbl_fc_tailieudotu": "Tài liệu đo từ",
  "tbl_fc_tailieudotrongluong": "Tài liệu đo trọng lượng",
  "tbl_fc_tailieudodien": "Tài liệu đo điện",
  "tbl_fc_tailieudoxa": "Tài liệu đo xạ",
  "tbl_fc_disandc": "Lớp di sản địa chất",
  "tbl_fc_magma": "Lớp thành tạo magma",
  "tbl_fc_tramtich": "Lớp Trầm tích",
  "tbl_fc_bienchat": "Lớp biến chất",
  "tbl_fc_dutgay": "Lớp đứt gãy",
  "tbl_fc_vanhphantandh": "Lớp vành phân tán địa hoá",
  "tbl_fc_diemdithuongdh": "Lớp điểm dị thường địa hoá",
  "tbl_fc_vanhphantants": "Lớp vành phân tán trọng sa",
  "tbl_fc_diemdithuongts": "Lớp điểm dị thường trọng sa",
  "tbl_fc_dctv_dcct": "Lớp Địa chất thủy văn - công trình",
  "tbl_fc_vungonhiem": "Lớp Vùng ô nhiễm",
  "tbl_fc_vungtruotlo": "Lớp Vùng trượt lở",
  "tbl_fc_vungdongdat": "Lớp Vùng tiềm năng động đất",
  "tbl_fc_khoangsannhole": "Lớp Khoáng sản nhỏ lẻ",
  "tbl_fc_vungtrienvongkhoangsan": "Lớp vùng triển vọng khoáng sản",
  "tbl_fc_kvcamhdks": "Lớp Khu vực cấm hoạt động khoáng sản",
  "tbl_fc_kvdtkhoangsan": "Lớp Khu vực dự trữ khoáng sản",
  "tbl_fc_dtchitiet": "Lớp Diện tích chi tiết",
  "tbl_fc_lotrinhdc": "Lộ trình địa chất",
  "tbl_fc_diemks": "Điểm khảo sát",
  "tbl_fc_nhatkydc": "Nhật ký địa chất",
  "tbl_fc_cthaovl": "Công trình hào (vết lộ)",
  "tbl_fc_ctgieng": "Công trình giếng",
  "tbl_fc_ctlo": "Công trình lò",
  "tbl_fc_lokhoan": "Bảng lỗ khoan",
  "tbl_fc_danhphapbd": "Danh pháp bản đồ",
  "tbl_fc_khudgks": "Khu vực triển vọng đã đánh giá",
  "tbl_fc_tqdientichdg": "Thân quặng diện tích đánh giá",
  "tbl_fc_khutdks": "Khu vực hoạt đông khoáng sản thăm dò",
  "tbl_fc_tqdientichtd": "Thân quặng diện tích thăm dò",
  "tbl_fc_vungtrienvongkhoangsandg": "Khu vực triển vọng đã đánh giá",
  "tbl_fc_khuvuctdkhoangsan": "Khu vực hoạt động thăm dò khoáng sản",
  "tbl_fc_khuvucktkhoangsan": "Khu vực hoạt động khai thác khoáng sản",
  "tbl_fc_dtcchung": "Diện tích chung",
  "tbl_tinh": "Ranh giới tỉnh",
  "tbl_huyen": "Ranh giới huyện",
  "tbl_xa": "Ranh giới xã"
}
