# -*- coding: utf-8 -*-

# DRIVER_SQL = '{SQL Server Native Client 11.0};'
DRIVER_SQL = '{SQL Server};'

# SERVER_SQL = '113.190.253.193,1433\\AZETSRV;'
SERVER_SQL = '222.252.27.8,1433\\AZETSRV;'
DATABASE_SQL = 'CSDLTayBacUAT;'
USER_SQL = 'taybac;'
PASSWORD_SQL = 'techvify@123;'

DATABASE_POSTGRES = 'ks'
USER_POSTGRES = 'postgres'
PASSWORD_POSTGRES = '1'
HOST_POSTGRES = '10.101.3.204'
PORT_POSTGRES = 5432

Rabbit = 'amqp://guest:guest@52.220.224.131:5672/%2f'

Mongo = 'mongodb://fimo:fimo!54321@10.101.3.204:27017/ks'
Mongo_db = "ks"
Mongo_collection = "map_services"

server = '10.101.3.204'
admin = "fimo"
password = "Mrvm3CVEvr8JGet9"

staticAgs = r"E:\SourceCode\tmact_2019\data\connect_information\ArcgisPublishServer.ags"
db = r'E:\SourceCode\tmact_2019\data\connect_information\ks_connection.sde'

OBJ_CASE = {
        "id_cthao": "ID_CTHao",
        "id_khudgks": "ID_KhuDGKS",
        "id_khutdks": "ID_KhuTDKS",
        "id_tqdientichdg": "ID_TQDienTichDG",
        "id_tqdientichtd": "ID_TQDienTichTD",
        "khoiluonglo": "KhoiLuongLo",
        "id_ctlo": "ID_CTLo",
        "khoiluonghaovl": "KhoiLuongHaoVL",
        "id_ctgieng": "ID_CTGieng",
        "khoiluonggieng": "KhoiLuongGieng",
        "mota_dks": "MoTa_DKS",
        "bieuhien": "BieuHien",
        "goccam_mattruot": "GocCam_MatTruot",
        "huongcam_mattruot": "HuongCam_MatTruot",
        "vitri": "ViTri",
        "tp_doikientao": "TP_DoiKienTao",
        "mucdobieuhien": "MucDoBieuHien",
        "tinhchatdutgay": "TinhChatDutGay",
        "id_diemks": "ID_DiemKS",
        "loaidks": "LoaiDKS",
        "hole_id": "Hole_ID",
        "chieusau": "ChieuSau",
        "ghi_chu": "Ghi_chu",
        "anh": "Anh",
        "bac_dt": "Bac_DT",
        "bacdithuong": "BacDiThuong",
        "bachamluong": "BacHamLuong",
        "banve": "BanVe",
        "baomat": "BaoMat",
        "caodohao": "CaoDoHao",
        "chieudai": "ChieuDai",
        "chubien": "ChuBien",
        "congthuckhoangvat": "CongThucKhoangVat",
        "dacdiem_dc": "Dacdiem_DC",
        "dacdiem_ks": "Dacdiem_KS",
        "danhphap_bd": "DanhPhap_BD",
        "dientich": "DienTich",
        "dientichcam": "DienTichCam",
        "docaogieng": "DoCaoGieng",
        "docaoh": "DoCaoH",
        "docaolo": "DoCaoLo",
        "doituongcam": "DoiTuongCam",
        "doituongdieutra": "DoiTuongDieuTra",
        "donviqd": "DonViQD",
        "donvith": "DonViTH",
        "dosaugieng": "DoSauGieng",
        "dosauhao": "DoSauHao",
        "file_anhnan": "File_AnhNan",
        "gioi": "Gioi",
        "gocnghieng": "GocNghieng",
        "hamluong": "HamLuong",
        "hamluong_tb": "Hamluong_TB",
        "he": "He",
        "hetoado": "HeToaDo",
        "hientrang": "HienTrang",
        "hientranglk": "HientrangLK",
        "hoathach": "HoaThach",
        "id": "ID",
        "id_da": "ID_DA",
        "id_danhphap": "ID_DanhPhap",
        "id_dvtc": "ID_DVTC",
        "id_ks": "ID_KS",
        "id_ks_dikem": "ID_KS_dikem",
        "id_nhomks": "ID_NhomKS",
        "id_tcdcks": "ID_TCDCKS",
        "id_tyle": "ID_Tyle",
        "isdean": "IsDeAn",
        "kh_kv": "Kh_kv",
        "kh_nguyento": "Kh_nguyento",
        "khlt": "KHLT",
        "khlt_bv": "KHLT_BV",
        "khoangvatkhac": "KhoangVatKhac",
        "khuvuc": "KhuVuc",
        "kinhtuyentruc": "KinhTuyenTruc",
        "kyhieukhoangvat": "KyHieuKhoangVat",
        "loai_ks": "Loai_KS",
        "loaicongtacdodien": "LoaiCongTacDoDien",
        "loaicongtacdotruongluc": "LoaiCongTacDoTruongLuc",
        "loaicongtacdotu": "LoaiCongTacDoTu",
        "loaicongtacdoxa": "LoaiCongTacDoXa",
        "loaidutgay": "LoaiDutGay",
        "mucdich": "MucDich",
        "mucdichkhoan": "MucDichKhoan",
        "mucdo_nc": "Mucdo_NC",
        "mucdonghiencuu": "MucDoNghienCuu",
        "muichieu": "MuiChieu",
        "namkt": "NamKT",
        "namnoplt": "NamNopLT",
        "namtc": "NamTC",
        "ngayketthuc": "NgayKetThuc",
        "ngaykhoicong": "NgayKhoiCong",
        "ngayqd": "NgayQD",
        "nguonvon": "NguonVon",
        "nhom": "Nhom",
        "nhomkhoangsan": "NhomKhoangSan",
        "nhomtobd": "NhomToBD",
        "pha": "Pha",
        "phuhetang": "PhuHeTang",
        "phuongkeodai": "PhuongKeoDai",
        "phuongphapdao": "PhuongPhapDao",
        "phuongphapkhoan": "PhuongphapKhoan",
        "phuongvi": "PhuongVi",
        "sh_diem": "SH_Diem",
        "sohieuhaovl": "SoHieuHaoVL",
        "sohieulo": "SoHieuLo",
        "sohieuvanh": "SoHieuVanh",
        "soqd": "SoQD",
        "tacgia": "Tacgia",
        "tap_phan": "Tap_Phan",
        "ten_kv": "Ten_kv",
        "ten_nguyento": "Ten_nguyento",
        "tenbando": "TenBanDo",
        "tenbanvekvdt": "TenBanVeKVDT",
        "tenbaocao": "TenBaoCao",
        "tenbc": "TenBC",
        "tenbv": "TenBV",
        "tendean": "TenDeAn",
        "tendiem": "TenDiem",
        "tendientich": "TenDienTich",
        "tengieng": "TenGieng",
        "tenhetang": "TenHeTang",
        "tenkhoangsan": "TenKhoangSan",
        "tenkhoangvat": "TenKhoangVat",
        "tenks": "TenKS",
        "tenkvcamhdks": "TenKVCamHDKS",
        "tenlk": "TenLK",
        "tenloaibd": "TenLoaiBD",
        "tennguyento": "TenNguyenTo",
        "tenphuche": "TenPhucHe",
        "tento": "TenTo",
        "tenvung": "TenVung",
        "thanhphanth": "ThanhPhanTH",
        "thietdokhoan": "ThietDoKhoan",
        "thong": "Thong",
        "tietdien": "TietDien",
        "tietdienlo": "TietDienLo",
        "toadomienglox": "ToaDoMiengLoX",
        "toadomiengloy": "ToaDoMiengLoY",
        "toadox": "ToaDoX",
        "toadoy": "ToaDoY",
        "toanvanqd": "ToanVanQD",
        "tuoidc": "TuoiDC",
        "tuong": "Tuong",
        "tuyen": "Tuyen",
        "tuyenhao": "TuyenHao",
        "tyle_bd": "Tyle_BD",
        "vitridialy": "ViTriDiaLy",
        "thoigiandt": "ThoiGianDT",
        "x": "X",
        "y": "Y",
        "z": "Z",
        "caodogieng": "CaoDoGieng",
        "chieudai_met": "ChieuDai_met",
        "chieudaituyen": "ChieuDaiTuyen",
        "chieurong": "ChieuRong",
        "chudautu": "ChuDauTu",
        "cqcapphep": "CQCapPhep",
        "cuongdodongdat": "CuongDoDongDat",
        "doanhnghiepkt": "DoanhNghiepKT",
        "donvithanhlap": "DonviThanhLap",
        "donvitn": "DonviTN",
        "donvitn_tl": "DonviTN_TL",
        "donvituvan": "DonViTuVan",
        "giayphepkt": "GiayPhepKT",
        "giaypheptd": "GiayPhepTD",
        "id_bienchat": "ID_BienChat",
        "id_captltn": "ID_CapTLTN",
        "id_dutgay": "ID_DutGay",
        "id_huyen": "ID_Huyen",
        "id_magma": "ID_Magma",
        "id_nhatky": "ID_NhatKy",
        "id_phieuctlo": "ID_PhieuCTLo",
        "id_tinh": "ID_Tinh",
        "id_tramtich": "ID_TramTich",
        "id_tuyenlt": "ID_TuyenLT",
        "id_xa": "ID_Xa",
        "khuvucks": "KhuVucKS",
        "khuvucnc": "KhuVucNC",
        "kyhieuks": "KyhieuKS",
        "kyhieunguyento": "KyHieuNguyenTo",
        "loaida": "LoaiDa",
        "loaids": "LoaiDS",
        "loaihinhcam": "LoaiHinhCam",
        "loaimau": "Loaimau",
        "loaionhiem": "LoaiONhiem",
        "mdnc": "MDNC",
        "mucdo": "Mucdo",
        "mucdobienchat": "MucdoBienChat",
        "nam": "Nam",
        "namxd": "NamXD",
        "ngayks": "NgayKS",
        "nguoiks": "NguoiKS",
        "nguon_tailieu": "Nguon_tailieu",
        "nhomdanhphap": "NhomDanhPhap",
        "objectid": "ObjectID",
        "phamvidongdat": "PhamViDongDat",
        "quimo": "QuiMo",
        "quymo": "QuyMo",
        "rgb_color": "RGB_Color",
        "soqdgiayphep": "SoQDGiayPhep",
        "tainguyen": "TaiNguyen",
        "tap": "Tap",
        "ten_bv": "Ten_BV",
        "tendanhphap": "TenDanhPhap",
        "tends": "TenDS",
        "tenkv": "TenKV",
        "tentuyen": "TenTuyen",
        "thenam": "TheNam",
        "tn_tl": "TN_TL",
        "truluong": "TruLuong",
        "tyle": "Tyle",
        "vitrihanhchinh": "ViTriHanhChinh",
        "id_khoangsannhole": "ID_khoangsannhole"
      }

LIST_SERVICE = {
  "tbl_fc_bandodiamao": "Lớp bản đồ địa mạo",
  "tbl_fc_tailieudotu": "Tài liệu đo từ",
  "tbl_fc_tailieudotrongluong": "Tài liệu đo trọng lượng",
  "tbl_fc_tailieudodien": "Tài liệu đo điện",
  "tbl_fc_tailieudoxa": "Tài liệu đo xạ",
  "tbl_fc_disandc": "Lớp di sản địa chất",
  "tbl_fc_magma": "Lớp thành tạo magma",
  "tbl_fc_tramtich": "Lớp Trầm tích",
  "tbl_fc_bienchat": "Lớp biến chất",
  "tbl_fc_dutgay": "Lớp đứt gãy",
  "tbl_fc_vanhphantandh": "Lớp vành phân tán địa hoá",
  "tbl_fc_diemdithuongdh": "Lớp điểm dị thường địa hoá",
  "tbl_fc_vanhphantants": "Lớp vành phân tán trọng sa",
  "tbl_fc_diemdithuongts": "Lớp điểm dị thường trọng sa",
  "tbl_fc_dctv_dcct": "Lớp Địa chất thủy văn - công trình",
  "tbl_fc_vungonhiem": "Lớp Vùng ô nhiễm",
  "tbl_fc_vungtruotlo": "Lớp Vùng trượt lở",
  "tbl_fc_vungdongdat": "Lớp Vùng tiềm năng động đất",
  "tbl_fc_khoangsannhole": "Lớp Khoáng sản nhỏ lẻ",
  "tbl_fc_vungtrienvongkhoangsan": "Lớp vùng triển vọng khoáng sản",
  "tbl_fc_kvcamhdks": "Lớp Khu vực cấm hoạt động khoáng sản",
  "tbl_fc_kvdtkhoangsan": "Lớp Khu vực dự trữ khoáng sản",
  "tbl_fc_dtchitiet": "Lớp Diện tích chi tiết",
  "tbl_fc_lotrinhdc": "Lộ trình địa chất",
  "tbl_fc_diemks": "Điểm khảo sát",
  "tbl_fc_cthaovl": "Công trình hào (vết lộ)",
  "tbl_fc_ctgieng": "Công trình giếng",
  "tbl_fc_ctlo": "Công trình lò",
  "tbl_fc_lokhoan": "Bảng lỗ khoan",
  "tbl_fc_danhphapbd": "Danh pháp bản đồ",
  "tbl_fc_khudgks": "Khu vực triển vọng đã đánh giá",
  "tbl_fc_tqdientichdg": "Thân quặng diện tích đánh giá",
  "tbl_fc_khutdks": "Khu vực hoạt đông khoáng sản thăm dò",
  "tbl_fc_tqdientichtd": "Thân quặng diện tích thăm dò",
  "tbl_fc_vungtrienvongkhoangsandg": "Khu vực triển vọng đã đánh giá",
  "tbl_fc_khuvuctdkhoangsan": "Khu vực hoạt động thăm dò khoáng sản",
  "tbl_fc_khuvucktkhoangsan": "Khu vực hoạt động khai thác khoáng sản",
  "tbl_fc_dtcchung": "Diện tích chung",
  "tbl_tinh": "Ranh giới tỉnh",
  "tbl_huyen": "Ranh giới huyện",
  "tbl_xa": "Ranh giới xã"
}
