# DRIVER_SQL = '{SQL Server Native Client 11.0};'
DRIVER_SQL = '{SQL Server};'

SERVER_SQL = '113.190.253.193,1433\\AZETSRV;'
DATABASE_SQL = 'CSDLTayBacUAT;'
USER_SQL = 'taybac;'
PASSWORD_SQL = 'techvify@123;'

DATABASE_POSTGRES = 'ks'
USER_POSTGRES = 'postgres'
PASSWORD_POSTGRES = '1'
HOST_POSTGRES = '10.101.3.204'
PORT_POSTGRES = 5432

Rabbit = 'amqp://guest:guest@52.220.224.131:5672/%2f'

Mongo = 'mongodb://fimo:fimo!54321@10.101.3.204:27017/ks'
Mongo_db = "ks"
Mongo_collection = "map_services"

server = '10.101.3.204'
admin = "fimo"
password = "Mrvm3CVEvr8JGet9"

staticAgs = r"E:\SourceCode\tmact_2019\data\connect_information\ArcgisPublishServer.ags"
db = r'E:\SourceCode\tmact_2019\data\connect_information\ks_connection.sde'

MATCHING_CASE = ['ID_NhatKy', 'TenTuyen', 'ChieuDaiTuyen', 'KhuVucNC', 'ID_TuyenLT', 'TenDiem',
                  'NgayKS', 'NguoiKS', 'Loaida', 'KhuVucKS', 'Loaimau', 'TheNam', 'SoHieuHaoVL',
                  'TuyenHao', 'PhuongVi', 'CaoDoHao', 'DoSauHao', 'TenGieng', 'Tuyen', 'CaoDoGieng',
                  'DoSauGieng', 'TietDien', 'Phuongphapdao', 'SoHieuLo', 'ToaDoMiengLoX',
                  'ToaDoMiengLoY', 'DoCaoLo', 'TietDienLo', 'ChieuRong', 'BanVe', 'Hole_ID', 'TenLK',
                  'ToaDoX', 'ToaDoY', 'DoCaoH', 'MucDichKhoan', 'BaoMat', 'PhuongphapKhoan',
                  'GocNghieng', 'NgayKhoiCong', 'NgayKetThuc', 'DonViTH', 'HientrangLK', 'TenBC',
                  'ThietDoKhoan', 'HeToaDo', 'KinhTuyenTruc', 'MuiChieu', 'TenDienTich',
                  'MucDoNghienCuu', 'MucDich', 'DoiTuongDieuTra', 'TenBanVeKVDT', 'Anh', 'Nhom',
                  'TruLuong', 'TaiNguyen', 'QuyMo', 'HienTrang', 'DacDiemDCKS', 'SoDiemKhepGoc',
                  'DienTich', 'GiayPhep', 'DoanhNghiep', 'ThoiGianHD', 'ID_NhomKS', 'TrienVongKS',
                  'TenKVCamHDKS', 'DoiTuongCam', 'DienTichCam', 'TenKVDTKhoangsan', 'ID_KS',
                  'DienTichDT', 'TL_TN', 'LoaiONhiem', 'NamXD', 'DiaDanh', 'MucDo', 'PhamViDongDat',
                  'CuongDoDongDat', 'Nguon_tailieu', 'TenKV', 'Ten_BV', 'TenDanhPhap', 'NhomDanhPhap',
                  'TenVung', 'LoaiCongTac', 'ViTriDiaLy', 'TenBV', 'KHLT_BV', 'TenBaoCao',
                  'File_AnhNan', 'TenDS', 'LoaiDS', 'ViTriHanhChinh', 'QuiMo', 'TenPhucHe', 'HoaThach',
                  'TenHeTang', 'TuoiDC', 'Gioi', 'He', 'Thong', 'ThanhPhanTH', 'NhomToBD', 'TenTo',
                  'ID_TyLe', 'MucdoBienChat', 'LoaiDutgay', 'Phuongkeodai', 'ChieuDai', 'ChuBien',
                  'NamNopLT', 'TenNguyenTo', 'KyHieuNguyenTo', 'BacDiThuong', 'TenKS', 'Ten_nguyento',
                  'Kh_nguyento', 'SoHieuVanh', 'TenKhoangVat', 'CongThucKhoangVat', 'BacHamLuong',
                  'TenKhoangSan', 'NhomKhoangSan', 'HamLuong', 'ID_DanhPhap', 'ID', 'ID_DA', 'SH_Diem',
                  'X', 'Y', 'ViTriDiaLy', 'Ten_kv', 'Kh_kv', 'Bac_DT', 'DanhPhap_BD', 'KHLT']

OBJ_CASE = {
  "objectid": "ObjectID",
  "anh": "Anh",
  "bac_dt": "Bac_DT",
  "bacdithuong": "BacDiThuong",
  "bachamluong": "BacHamLuong",
  "banve": "BanVe",
  "baomat": "BaoMat",
  "caodohao": "CaoDoHao",
  "chieudai": "ChieuDai",
  "chubien": "ChuBien",
  "congthuckhoangvat": "CongThucKhoangVat",
  "dacdiem_dc": "Dacdiem_DC",
  "dacdiem_ks": "Dacdiem_KS",
  "danhphap_bd": "DanhPhap_BD",
  "dientich": "DienTich",
  "dientichcam": "DienTichCam",
  "docaogieng": "DoCaoGieng",
  "docaoh": "DoCaoH",
  "docaolo": "DoCaoLo",
  "doituongcam": "DoiTuongCam",
  "doituongdieutra": "DoiTuongDieuTra",
  "donviqd": "DonViQD",
  "donvith": "DonViTH",
  "dosaugieng": "DoSauGieng",
  "dosauhao": "DoSauHao",
  "file_anhnan": "File_AnhNan",
  "gioi": "Gioi",
  "gocnghieng": "GocNghieng",
  "hamluong": "HamLuong",
  "hamluong_tb": "Hamluong_TB",
  "he": "He",
  "hetoado": "HeToaDo",
  "hientrang": "HienTrang",
  "hientranglk": "HienTrangLK",
  "hoathach": "HoaThach",
  "id": "ID",
  "id_da": "ID_DA",
  "id_danhphap": "ID_DanhPhap",
  "id_dvtc": "ID_DVTC",
  "id_ks": "ID_KS",
  "id_ks_dikem": "ID_KS_dikem",
  "id_nhomks": "ID_NhomKS",
  "id_tcdcks": "ID_TCDCKS",
  "id_tyle": "ID_Tyle",
  "isdean": "IsDeAn",
  "kh_kv": "Kh_kv",
  "kh_nguyento": "Kh_nguyento",
  "khlt": "KHLT",
  "khlt_bv": "KHLT_BV",
  "khoangvatkhac": "KhoangVatKhac",
  "khuvuc": "KhuVuc",
  "kinhtuyentruc": "KinhTuyenTruc",
  "kyhieukhoangvat": "KyHieuKhoangVat",
  "loai_ks": "Loai_KS",
  "loaicongtacdodien": "LoaiCongTacDoDien",
  "loaicongtacdotruongluc": "LoaiCongTacDoTruongLuc",
  "loaicongtacdotu": "LoaiCongTacDoTu",
  "loaicongtacdoxa": "LoaiCongTacDoXa",
  "loaidutgay": "LoaiDutgay",
  "mucdich": "MucDich",
  "mucdichkhoan": "MucDichKhoan",
  "mucdo_nc": "Mucdo_NC",
  "mucdonghiencuu": "MucDoNghienCuu",
  "muichieu": "MuiChieu",
  "namkt": "NamKT",
  "namnoplt": "NamNopLT",
  "namtc": "NamTC",
  "ngayketthuc": "NgayKetThuc",
  "ngaykhoicong": "NgayKhoiCong",
  "ngayqd": "NgayQD",
  "nguonvon": "NguonVon",
  "nhom": "Nhom",
  "nhomkhoangsan": "NhomKhoangSan",
  "nhomtobd": "NhomToBD",
  "pha": "Pha",
  "phuhetang": "PhuHeTang",
  "phuongkeodai": "Phuongkeodai",
  "phuongphapdao": "PhuongPhapDao",
  "phuongphapkhoan": "PhuongPhapKhoan",
  "phuongvi": "PhuongVi",
  "sh_diem": "SH_Diem",
  "sohieuhaovl": "SoHieuHaoVL",
  "sohieulo": "SoHieuLo",
  "sohieuvanh": "SoHieuVanh",
  "soqd": "SoQD",
  "tacgia": "Tacgia",
  "tap_phan": "Tap_Phan",
  "ten_kv": "Ten_KV",
  "ten_nguyento": "Ten_nguyento",
  "tenbando": "TenBanDo",
  "tenbanvekvdt": "TenBanVeKVDT",
  "tenbaocao": "TenBaoCao",
  "tenbc": "TenBC",
  "tenbv": "TenBV",
  "tendean": "TenDeAn",
  "tendiem": "TenDiem",
  "tendientich": "TenDienTich",
  "tengieng": "TenGieng",
  "tenhetang": "TenHeTang",
  "tenkhoangsan": "TenKhoangSan",
  "tenkhoangvat": "TenKhoangVat",
  "tenks": "TenKS",
  "tenkvcamhdks": "TenKVCamHDKS",
  "tenlk": "TenLK",
  "tenloaibd": "TenLoaiBD",
  "tennguyento": "TenNguyenTo",
  "tenphuche": "TenPhucHe",
  "tento": "TenTo",
  "tenvung": "TenVung",
  "thanhphanth": "ThanhPhanTH",
  "thietdokhoan": "ThietDoKhoan",
  "thong": "Thong",
  "tietdien": "TietDien",
  "tietdienlo": "TietDienLo",
  "toadomienglox": "ToaDoMiengLoX",
  "toadomiengloy": "ToaDoMiengLoY",
  "toadox": "ToaDoX",
  "toadoy": "ToaDoY",
  "toanvanqd": "ToanVanQD",
  "tuoidc": "TuoiDC",
  "tuong": "Tuong",
  "tuyen": "Tuyen",
  "tuyenhao": "TuyenHao",
  "tyle_bd": "Tyle_BD",
  "vitridialy": "ViTriDiaLy",
  "x": "X",
  "y": "Y",
  "z": "Z"
}
